# application
application: atomgen
version: 1
runtime: python
api_version: 1

# urls
handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /css
  static_dir: static/css

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /gen/1
  script: main.py
  login: admin

- url: /gen/5
  script: main.py
  login: admin

- url: /.*
  script: main.py
